- hosts: flaskserver
  user: ec2-user
  become: yes
  vars:
    app_port: 8000  # Change this value if needed

  tasks:
    - name: Install required packages
      yum:
        name:
          - python3
          - python3-pip
          - nginx
          - git
        state: present

    - name: Install Gunicorn and Flask
      pip:
        name:
          - flask
          - gunicorn
          - joblib
          - scikit-learn

    - name: Upgrade Gunicorn globally
      command: pip3 install --upgrade gunicorn

    - name: Clone Flask application from GitHub
      git:
        repo: https://github.com/tupakulamanoj/cardio_heart_detection.git
        dest: /home/ec2-user/cardio_heart_detection
        version: main

    - name: Configure Gunicorn systemd service
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve Flask app
          After=network.target
          
          [Service]
          User=ec2-user
          Group=ec2-user
          WorkingDirectory=/home/ec2-user/cardio_heart_detection
          Environment="FLASK_RUN_PORT={{ app_port }}"
          ExecStart=/usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:{{ app_port }} main:app
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Configure Nginx for Flask
      copy:
        dest: /etc/nginx/conf.d/flaskapp.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:{{ app_port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Remove default Nginx config (if exists)
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
