- hosts: all
  user: ec2-user
  become: yes
  vars:
    app_port: 4080  # Change this value if needed

  tasks:
    - name: Install required system packages
      yum:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Enable and install nginx using amazon-linux-extras
      shell: |
        sudo amazon-linux-extras enable nginx1
        sudo yum clean metadata
        sudo yum install -y nginx

    - name: Ensure pip is installed
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install Python dependencies
      pip:
        name:
          - flask
          - gunicorn
          - joblib
          - scikit-learn
          - bs4
          - requests
        executable: pip3

    - name: Clone Flask application from GitHub
      git:
        repo: https://github.com/janardhan19-git/my-app.git
        dest: /home/ec2-user/cardio_heart_detection
        version: main

    - name: Configure Gunicorn systemd service
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve Flask app
          After=network.target
          
          [Service]
          User=ec2-user
          Group=ec2-user
          WorkingDirectory=/home/ec2-user/cardio_heart_detection
          Environment="FLASK_RUN_PORT={{ app_port }}"
          ExecStart=/usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:{{ app_port }} application:application
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Configure Nginx for Flask
      copy:
        dest: /etc/nginx/conf.d/flaskapp.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:{{ app_port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes